version: '3'

services:
  coordinator:
    image: "lewuathe/presto-coordinator:${PRESTO_VERSION}"
    ports:
      - "8080:8080"
    container_name: "coordinator"
    command: coordinator
  worker:
    image: "lewuathe/presto-worker:${PRESTO_VERSION}"
    depends_on:
      - coordinator
    deploy:
      replicas: 3
    container_name: "worker"
    ports:
      - "8081:8081"
    command: worker